name: deploy-expiration

on:
  push:
    branches:
      - main
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PAT
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      - run: cd expiration && docker build -t taseenjunaid/gp-expiration .
      - run: docker push taseenjunaid/gp-expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save gildedpass
      - run: kubectl rollout restart deployment expiration-depl
